variables:
    CONTAINER_RELEASE_IMAGE_BASE: $CI_REGISTRY/images/k-link

before_script:
  - export IMAGE_TAG="${CI_COMMIT_REF_NAME#v}_${CI_COMMIT_SHA:0:10}"
  - export CLEANED_CI_COMMIT_REF_NAME="${CI_COMMIT_REF_NAME#v}"
  - echo $IMAGE_TAG

generate_docker:
  stage: build
  tags:
    - shell
    - deploy
  script:
    - docker build -t $CI_REGISTRY_IMAGE:${IMAGE_TAG} .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:${IMAGE_TAG}

tagged_release:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:${IMAGE_TAG}
    - docker login -u $REGISTRY_RELEASE_USERNAME -p $REGISTRY_RELEASE_PASSWORD $CI_REGISTRY
    - docker tag $CI_REGISTRY_IMAGE:${IMAGE_TAG} "$CONTAINER_RELEASE_IMAGE_BASE:${CLEANED_CI_COMMIT_REF_NAME}"
    - docker tag $CI_REGISTRY_IMAGE:${IMAGE_TAG} "$CONTAINER_RELEASE_IMAGE_BASE:latest"
    - docker push "$CONTAINER_RELEASE_IMAGE_BASE:latest"
    - docker push "$CONTAINER_RELEASE_IMAGE_BASE:${CLEANED_CI_COMMIT_REF_NAME}"
  tags:
    - shell
    - deploy
  only:
    - tags